### ISSUE TITLE
Fedora clashes in /usr/bin

### ISSUE THREAD

**Issue by keithy** [skarnet/execline#2]
I would like to us execline in Fedora, and Fedora CoreOS attempting to install using: https://fedora.pkgs.org/31/rpm-sphere-x86_64/execline-devel-2.3.0.4-7.1.x86_64.rpm.html
```
error: Checkout execline-2.3.0.4-7.1.x86_64: Hardlinking 9c/8aa019367d3a8fa2545da722c3c4e2aabc9fd35c1e9a46cc33f1342f781454.file to cd: File exists
```
Would it be preferable to use an alternative path?

**Comment by skarnet** [comment]
It means this rpm has not been packaged correctly. It is also obsolete: the current version of execline is 2.5.3.0.
My suggestion is not to use the rpm and install execline manually instead. You can use the --enable-pedantic-posix option to get a fully POSIX-compliant `cd` binary from execline, and use it as `/usr/bin/cd` or `/bin/cd` while putting the existing (useless) `/usr/bin/cd` from Fedora out of the way.

**Comment by skarnet** [comment]
Closing this.
