### ISSUE TITLE
importas bug

### ISSUE THREAD

**Issue by guijun** [skarnet/execline#3]
reproduce:
backtick PWD { pwd }
importas MYPATH PWD
foreground
{ mkdir -p /logs${MYPATH} }
take a look at /logs
there is a ? in the path

**Comment by skarnet** [comment]
Not a bug. `pwd` prints a newline and you're not chomping it, so it appears verbatim in the PWD variable and in the MYPATH substitution.
What you want is `backtick -n PWD { pwd }`. The `-n` option chomps the trailing newline.

**Comment by guijun** [comment]
thanks.
